name: CI for EntryTracker

on:
  push:
    branches:
      - main

jobs:
  build-test-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run unit test (curl)
        run: |
          nohup python app.py &
          sleep 5
          curl http://localhost:5000

      - name: Build Docker image
        run: |
          docker build -t entrytracker-app .

      - name: Run E2E tests using docker-compose
        run: |
          docker compose up -d
          sleep 10
          curl http://localhost:5000
          docker compose down

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push image to Docker Hub
        run: |
          docker tag entrytracker-app ${{ secrets.DOCKER_USERNAME }}/entrytracker-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/entrytracker-app:latest
